### ISSUE TITLE
Github Action에서 Toolchain을 설정했을 때.. Java Home 설정?

### ISSUE THREAD

**Issue by fp024** [fp024/struts2-study#4]
툴체인 설정을 해보고 있는데...

처음에는 너무 안되어서 어떤 분이 만들어둔 액션 플러그인을 사용했는데..

* https://github.com/cactuslab/maven-toolchains-xml-action
```yml
   - uses: cactuslab/maven-toolchains-xml-action@v1
     with:
       toolchains: |
       [
         {"jdkVersion": "8", "jdkHome": "${{ env.JAVA_HOME }}"}
       ]
```

더 진행하다보니...

setup-java 플러그인에서 툴체인을 지원하고 있었다.

* https://github.com/actions/setup-java

툴체인을 설정하면, 

첫 JDK설정시 프로젝트 루트에다 toolchains.xml를 만들고,  이후 버전마다 덮어쓰기 append를 한다.
```
  Creating toolchains.xml for JDK version 8 from Eclipse Temurin
  Writing to /home/runner/work/struts2-study/struts2-study/toolchains.xml
  ...
  Overwriting existing file /home/runner/work/struts2-study/struts2-study/toolchains.xml
```

여기서 중요한 점은 toolchains.xml을 `~/.m2` 경로에 위치하지 않기 때문에...

maven 실행 명령에 `-t`를 붙여 toolchains.xml 경로를 지정하면 된다.

```yml
    - name: Build with Maven (struts2-junit5-user-custom-plugin install)
      run: mvn -B clean install --file pom.xml -t toolchains.xml

    - name: Build with Maven (Projects)
      run: mvn -B clean test --file struts2-study-parent/pom.xml -t toolchains.xml
```

커밋로그가 너무 많이 생겼지만 ... 😓 설정은 잘 완료하였다. 👍

* https://github.com/fp024/struts2-study/blob/master/.github/workflows/maven-build.yml
